'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")>  _
        Public Property SMTPServerName() As String
            Get
                Return CType(Me("SMTPServerName"),String)
            End Get
            Set
                Me("SMTPServerName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("user@gmail.com")>  _
        Public Property SMTPUserName() As String
            Get
                Return CType(Me("SMTPUserName"),String)
            End Get
            Set
                Me("SMTPUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SMTPPassword() As String
            Get
                Return CType(Me("SMTPPassword"),String)
            End Get
            Set
                Me("SMTPPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public Property SMTPPort() As Integer
            Get
                Return CType(Me("SMTPPort"),Integer)
            End Get
            Set
                Me("SMTPPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableSSL() As Boolean
            Get
                Return CType(Me("EnableSSL"),Boolean)
            End Get
            Set
                Me("EnableSSL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("user@gmail.com")>  _
        Public Property MailFrom() As String
            Get
                Return CType(Me("MailFrom"),String)
            End Get
            Set
                Me("MailFrom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Authentication() As Boolean
            Get
                Return CType(Me("Authentication"),Boolean)
            End Get
            Set
                Me("Authentication") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SystemPassword() As String
            Get
                Return CType(Me("SystemPassword"),String)
            End Get
            Set
                Me("SystemPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Front Lobby")>  _
        Public Property LocationName() As String
            Get
                Return CType(Me("LocationName"),String)
            End Get
            Set
                Me("LocationName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SelectCamera() As Integer
            Get
                Return CType(Me("SelectCamera"),Integer)
            End Get
            Set
                Me("SelectCamera") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Hello. All visitors please sign"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"in and out here.")>  _
        Public Property WelcomeText() As String
            Get
                Return CType(Me("WelcomeText"),String)
            End Get
            Set
                Me("WelcomeText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Please start by entering your information."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Click the picture to take your webcam"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"photo and announce your arrival. Thank you.")>  _
        Public Property SignInInstructions() As String
            Get
                Return CType(Me("SignInInstructions"),String)
            End Get
            Set
                Me("SignInInstructions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Your Name")>  _
        Public Property NameText() As String
            Get
                Return CType(Me("NameText"),String)
            End Get
            Set
                Me("NameText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Your Company")>  _
        Public Property CompanyText() As String
            Get
                Return CType(Me("CompanyText"),String)
            End Get
            Set
                Me("CompanyText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Who are you here to see?")>  _
        Public Property VisitingText() As String
            Get
                Return CType(Me("VisitingText"),String)
            End Get
            Set
                Me("VisitingText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sign In")>  _
        Public Property SignInButtonText() As String
            Get
                Return CType(Me("SignInButtonText"),String)
            End Get
            Set
                Me("SignInButtonText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sign Out")>  _
        Public Property SignOutButtonText() As String
            Get
                Return CType(Me("SignOutButtonText"),String)
            End Get
            Set
                Me("SignOutButtonText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BackgroundImage() As String
            Get
                Return CType(Me("BackgroundImage"),String)
            End Get
            Set
                Me("BackgroundImage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15, 48, 99")>  _
        Public Property WelcomeBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("WelcomeBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("WelcomeBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property FontColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("FontColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("FontColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property VisitorLogLocation() As String
            Get
                Return CType(Me("VisitorLogLocation"),String)
            End Get
            Set
                Me("VisitorLogLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Thank you for signing out")>  _
        Public Property SignOutText() As String
            Get
                Return CType(Me("SignOutText"),String)
            End Get
            Set
                Me("SignOutText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("%u has been notified")>  _
        Public Property NotifyText() As String
            Get
                Return CType(Me("NotifyText"),String)
            End Get
            Set
                Me("NotifyText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Century Gothic, 14pt")>  _
        Public Property FontName() As Global.System.Drawing.Font
            Get
                Return CType(Me("FontName"),Global.System.Drawing.Font)
            End Get
            Set
                Me("FontName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseMotionDetection() As Boolean
            Get
                Return CType(Me("UseMotionDetection"),Boolean)
            End Get
            Set
                Me("UseMotionDetection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Hello.  All visitors please sign in and out here.")>  _
        Public Property WelcomeMessage() As String
            Get
                Return CType(Me("WelcomeMessage"),String)
            End Get
            Set
                Me("WelcomeMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property MotionSensitivity() As Integer
            Get
                Return CType(Me("MotionSensitivity"),Integer)
            End Get
            Set
                Me("MotionSensitivity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property VideoSource() As Integer
            Get
                Return CType(Me("VideoSource"),Integer)
            End Get
            Set
                Me("VideoSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EmailNotifications() As Boolean
            Get
                Return CType(Me("EmailNotifications"),Boolean)
            End Get
            Set
                Me("EmailNotifications") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Your E-mail Address")>  _
        Public Property EmailText() As String
            Get
                Return CType(Me("EmailText"),String)
            End Get
            Set
                Me("EmailText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EmailVisible() As Boolean
            Get
                Return CType(Me("EmailVisible"),Boolean)
            End Get
            Set
                Me("EmailVisible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CompanyVisible() As Boolean
            Get
                Return CType(Me("CompanyVisible"),Boolean)
            End Get
            Set
                Me("CompanyVisible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VisitorBadgePrinting() As Boolean
            Get
                Return CType(Me("VisitorBadgePrinting"),Boolean)
            End Get
            Set
                Me("VisitorBadgePrinting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EmployeeDirectoryLocation() As String
            Get
                Return CType(Me("EmployeeDirectoryLocation"),String)
            End Get
            Set
                Me("EmployeeDirectoryLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property MotionDelay() As Integer
            Get
                Return CType(Me("MotionDelay"),Integer)
            End Get
            Set
                Me("MotionDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailChimpAPIKey() As String
            Get
                Return CType(Me("MailChimpAPIKey"),String)
            End Get
            Set
                Me("MailChimpAPIKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailChimpListID() As String
            Get
                Return CType(Me("MailChimpListID"),String)
            End Get
            Set
                Me("MailChimpListID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseMailChimp() As Boolean
            Get
                Return CType(Me("UseMailChimp"),Boolean)
            End Get
            Set
                Me("UseMailChimp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CameraResolutionIndex() As Integer
            Get
                Return CType(Me("CameraResolutionIndex"),Integer)
            End Get
            Set
                Me("CameraResolutionIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SnapshotResolutionIndex() As Integer
            Get
                Return CType(Me("SnapshotResolutionIndex"),Integer)
            End Get
            Set
                Me("SnapshotResolutionIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseFaceDetection() As Boolean
            Get
                Return CType(Me("UseFaceDetection"),Boolean)
            End Get
            Set
                Me("UseFaceDetection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseTouchUI() As Boolean
            Get
                Return CType(Me("UseTouchUI"),Boolean)
            End Get
            Set
                Me("UseTouchUI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PrinterIndex() As Integer
            Get
                Return CType(Me("PrinterIndex"),Integer)
            End Get
            Set
                Me("PrinterIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CompanyLogo() As String
            Get
                Return CType(Me("CompanyLogo"),String)
            End Get
            Set
                Me("CompanyLogo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Please scan your visitor badge or select"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"your name and click your picture. Thank"& _ 
            " You.")>  _
        Public Property SignOutInstructions() As String
            Get
                Return CType(Me("SignOutInstructions"),String)
            End Get
            Set
                Me("SignOutInstructions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Please select your name")>  _
        Public Property SignOutVisitor() As String
            Get
                Return CType(Me("SignOutVisitor"),String)
            End Get
            Set
                Me("SignOutVisitor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 100, 255")>  _
        Public Property SignInButtonColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SignInButtonColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SignInButtonColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15, 48, 99")>  _
        Public Property SignInBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SignInBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SignInBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15, 48, 99")>  _
        Public Property SignOutBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SignOutBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SignOutBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 100, 255")>  _
        Public Property SignOutButtonColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SignOutButtonColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SignOutButtonColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseVisitorDetection() As Boolean
            Get
                Return CType(Me("UseVisitorDetection"),Boolean)
            End Get
            Set
                Me("UseVisitorDetection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property EmailServerType() As Integer
            Get
                Return CType(Me("EmailServerType"),Integer)
            End Get
            Set
                Me("EmailServerType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property FaceDetectionSensitivity() As Integer
            Get
                Return CType(Me("FaceDetectionSensitivity"),Integer)
            End Get
            Set
                Me("FaceDetectionSensitivity") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")> _
        Friend ReadOnly Property Settings() As Global.Receptio.My.MySettings
            Get
                Return Global.Receptio.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
